"""
Django settings for Sengladmin project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

import djcelery
djcelery.setup_loader()
BROKER_URL = 'django://'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')aevg*js(cf*-ya)c3v48ln42oe_bug3ettckx=@oyq&zu@6e9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djcelery',
    'kombu.transport.django',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sengladmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Sengladmin/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sengladmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

# LOGGING
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            #'format': '[%(asctime)s] [%(process)d] [%(thread)d] [%(module)s] [%(filename)s:%(lineno)s] [%(levelname)s] %(message)s'
            'format': '[%(asctime)s] [%(process)d] [%(thread)d] [%(filename)16s:%(lineno)4d] [%(levelname)-6s] %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'formatter': 'standard',
            'class': 'logging.FileHandler',
            'filename': '/var/log/sengladmin/platform.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


# Cache
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': '127.0.0.1:6379',
        'OPTIONS': {
            'DB': 0,
            'PASSWORD': '',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 500,
                'timeout': 20,
            }
        },
    },
}

# Cache Session
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

LOGIN_URL = '/sengladmin/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(__file__), 'static')
STATICFILES_DIRS = (
    ('css',os.path.join(STATIC_ROOT,'css').replace('\\','/') ),
    ('js',os.path.join(STATIC_ROOT,'js').replace('\\','/') ),
    ('image',os.path.join(STATIC_ROOT,'image').replace('\\','/') ),
    ('fonts',os.path.join(STATIC_ROOT,'fonts').replace('\\','/') ),
)

# celery
CELERY_RESULT_BACKEND = "mongodb"
CELERY_MONGODB_BACKEND_SETTINGS = {
    'host': '127.0.0.1',
    'port': '27017',
    'user': 'sengladmin',
    'password': 'sengladmin',
    'database': 'monitor',
    #"taskmeta_collection": "my_taskmeta" # Collection name to use for task output
    'taskmeta_collection': 'taskmeta',
    'maxpoolsize': 10
}
CELERYD_LOG_FILE = '/var/log/sengladmin/celery.log'
CELERYD_LOG_FORMAT = '[%(asctime)s] [%(processName)s] [%(levelname)s] %(message)s'
CELERYD_TASK_LOG_FORMAT = '[%(asctime)s] [%(processName)s] [%(levelname)s] [%(task_name)s] [%(task_id)s] [%(filename)s:%(lineno)s] %(message)s'
CELERYD_LOG_LEVEL = 'DEBUG'

BROKER_BACKEND = 'mongodb'
BROKER_URL = 'mongodb://sengladmin:sengladmin@127.0.0.1:27017/monitor'
CELERY_IMPORTS = ('sengladmin.tasks',)

APPEND_SLASH = False

# custom
MAIL_OUTBOX = 'services@sengled.com'
MAIL_SUBJECT_REGISTER = 'SenglAdmin REGISTER CAPTCHA'
MAIL_SUBJECT_RESETPASS = 'SenglAdmin RESET PASSWORD'
MAIL_SUBJECT_DEPLOY = 'SenglAdmin Deploy Result'

MONGODB = {
    'default': {
        'NAME': 'monitor',
        'USER': 'sengladmin',
        'PASSWORD': 'sengladmin',
        'HOST': '127.0.0.1',
        'PORT': '27017',
    }
}

PACKAGE_SAVE_PATH = '/var/sengladmin/packages'
SQL_SAVE_PATH = '/var/sengladmin/sql'

INCEPTION_HOST = '127.0.0.1'
INCEPTION_PORT = 6669

DEPLOY_SINGLE_TIMEOUT = 120

APPEND_SLASH = False

# jenkins
JENKINS_HOST = '127.0.0.1'
JENKINS_PORT = 9090
JENKINS_USER = 'root'
JENKINS_PASS = 'Sengled@!@#$'
TEMPLATE_JENKINS_CONFIG_XML = os.path.join(os.path.dirname(__file__), 'templates', 'files', 'JENKINS_CONFIG.xml')
JENKINS_BUILD_TRIGGER = '/var/sengladmin/build-scripts/build-package.py'
